name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings --html=reports/test_report.html --self-contained-html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: reports/test_report.html